// src/components/dashboard/marketing/GoogleFeedTab.jsx
//
// Hands the vendor one URL to paste into Google Merchant Center.
//
// Merchant Center free listings put products on Google Search, the Shopping tab
// and Google Images at no cost, and Nigeria is supported. For a vendor with no
// ad budget that is the cheapest customer acquisition available, which is why
// this sits in Marketing rather than in a settings screen.
//
// The feed itself is generated by product-feed.js and refetched by Google on a
// schedule, so the catalogue stays in sync with no further work from the vendor.
// This screen is only the handover: the link, the prerequisites, and the steps.
import { useState } from 'react'
import { Copy, Check, ExternalLink, ShoppingBag, Lock, AlertCircle } from 'lucide-react'

const STEPS = [
  {
    title: 'Create a free Merchant Center account',
    body: 'Go to Google Merchant Center and sign up with the Google account you use for your business. It is free.',
    link: 'https://merchants.google.com/',
    linkLabel: 'Open Merchant Center',
  },
  {
    title: 'Confirm your website',
    body: 'Merchant Center will ask you to verify and claim your store address. Paste your store link when it asks for your website.',
  },
  {
    title: 'Add your feed',
    body: 'Under Products, choose to add a product source and pick the scheduled fetch option. Paste the feed link below as the file URL and set it to fetch daily.',
  },
  {
    title: 'Turn on free listings',
    body: 'In the free listings section, opt in. Google reviews new accounts, which usually takes a few days, then your products can start showing in search results at no cost.',
  },
]

export default function GoogleFeedTab({ store, storeUrl, seoActive, eligible }) {
  const [copied, setCopied] = useState('')

  const slug = store?.storeName || ''
  const feedUrl = `https://sellapage.com.ng/${slug}/feed.xml`
  const publicUrl = storeUrl || `https://sellapage.com.ng/${slug}`

  const copy = (value, key) => {
    navigator.clipboard?.writeText(value)
    setCopied(key)
    setTimeout(() => setCopied(''), 2000)
  }

  const ready = eligible && seoActive

  return (
    <div className="space-y-4">
      <div className="rounded-2xl border border-gray-100 bg-white p-4">
        <div className="flex items-start gap-2.5">
          <div className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-xl bg-blue-50">
            <ShoppingBag size={17} className="text-blue-600" />
          </div>
          <div className="min-w-0">
            <p className="text-sm font-bold text-gray-900">Free listings on Google</p>
            <p className="mt-0.5 text-xs leading-relaxed text-gray-500">
              Put your products on Google Search and the Shopping tab without paying for ads.
              Sellapage keeps the product list up to date for you, so you only do this once.
            </p>
          </div>
        </div>
      </div>

      {!eligible && (
        <div className="flex items-start gap-2.5 rounded-2xl border border-amber-200 bg-amber-50 p-4">
          <Lock size={16} className="mt-0.5 flex-shrink-0 text-amber-600" />
          <div>
            <p className="text-sm font-bold text-amber-900">Available on Growth and above</p>
            <p className="mt-0.5 text-xs leading-relaxed text-amber-800">
              Upgrade to publish your catalogue to Google.
            </p>
          </div>
        </div>
      )}

      {eligible && !seoActive && (
        <div className="flex items-start gap-2.5 rounded-2xl border border-amber-200 bg-amber-50 p-4">
          <AlertCircle size={16} className="mt-0.5 flex-shrink-0 text-amber-600" />
          <div>
            <p className="text-sm font-bold text-amber-900">Turn on indexing first</p>
            <p className="mt-0.5 text-xs leading-relaxed text-amber-800">
              Your feed stays private until you switch on search engine and AI indexing in Get Found.
              That switch is what tells us you want to be listed publicly.
            </p>
          </div>
        </div>
      )}

      <div className={`rounded-2xl border border-gray-100 bg-white p-4 ${ready ? '' : 'opacity-60'}`}>
        <p className="text-xs font-bold text-gray-700">Your feed link</p>
        <p className="mt-0.5 text-[11px] text-gray-400">Paste this into Merchant Center. Do not share it as your shop link.</p>
        <div className="mt-2 flex items-center gap-2 rounded-xl border border-gray-200 bg-gray-50 px-3 py-2">
          <span className="min-w-0 flex-1 truncate font-mono text-[11px] text-gray-700">{feedUrl}</span>
          <button
            type="button"
            disabled={!ready}
            onClick={() => copy(feedUrl, 'feed')}
            className="flex-shrink-0 rounded-lg bg-gray-900 px-2.5 py-1.5 text-[11px] font-bold text-white disabled:bg-gray-200 disabled:text-gray-400"
          >
            {copied === 'feed' ? <Check size={12} /> : <Copy size={12} />}
          </button>
        </div>

        <p className="mt-3 text-xs font-bold text-gray-700">Your store link</p>
        <p className="mt-0.5 text-[11px] text-gray-400">Merchant Center asks for this when it verifies your website.</p>
        <div className="mt-2 flex items-center gap-2 rounded-xl border border-gray-200 bg-gray-50 px-3 py-2">
          <span className="min-w-0 flex-1 truncate font-mono text-[11px] text-gray-700">{publicUrl}</span>
          <button
            type="button"
            onClick={() => copy(publicUrl, 'store')}
            className="flex-shrink-0 rounded-lg bg-gray-900 px-2.5 py-1.5 text-[11px] font-bold text-white"
          >
            {copied === 'store' ? <Check size={12} /> : <Copy size={12} />}
          </button>
        </div>
      </div>

      <div className="rounded-2xl border border-gray-100 bg-white p-4">
        <p className="mb-3 text-sm font-bold text-gray-900">How to set it up</p>
        <ol className="space-y-3">
          {STEPS.map((s, i) => (
            <li key={s.title} className="flex gap-3">
              <span className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-gray-900 text-[11px] font-bold text-white">
                {i + 1}
              </span>
              <div className="min-w-0">
                <p className="text-xs font-bold text-gray-900">{s.title}</p>
                <p className="mt-0.5 text-[11px] leading-relaxed text-gray-500">{s.body}</p>
                {s.link && (
                  <a
                    href={s.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="mt-1 inline-flex items-center gap-1 text-[11px] font-bold text-blue-600 hover:underline"
                  >
                    {s.linkLabel} <ExternalLink size={11} />
                  </a>
                )}
              </div>
            </li>
          ))}
        </ol>
      </div>

      <div className="rounded-2xl border border-gray-100 bg-gray-50/70 p-4">
        <p className="text-xs font-bold text-gray-700">What gets sent</p>
        <ul className="mt-1.5 space-y-1 text-[11px] leading-relaxed text-gray-500">
          <li>Name, description, photo, price and stock status for each product.</li>
          <li>Items with no photo, no price, or that you have hidden are left out, because Google rejects them.</li>
          <li>Prices are sent in naira, exactly as you set them.</li>
          <li>Google refetches on its own, so new products appear without you doing anything.</li>
        </ul>
      </div>
    </div>
  )
}
