// src/components/dashboard/marketing/GoogleFeedTab.jsx
//
// Hands the vendor one URL to paste into Google Merchant Center.
//
// Merchant Center free listings put products on Google Search, the Shopping tab
// and Google Images at no cost, and Nigeria is supported. For a vendor with no
// ad budget that is the cheapest customer acquisition available, which is why
// this sits in Marketing rather than in a settings screen.
//
// The feed itself is generated by product-feed.js and refetched by Google on a
// schedule, so the catalogue stays in sync with no further work from the vendor.
// This screen is only the handover: the link, the prerequisites, and the steps.
//
// Redesigned 2026-10-08 to match Get found: the setup on the left; on the right
// how the vendor's own products would look in Google Shopping, and which of
// them would be left out of the feed and why (the same rules product-feed.js
// applies: active, priced, named, with a photo). It uses the products the
// dashboard already loaded, so it costs no extra reads.
import { ShoppingBag, CheckCircle2, Circle, ImageOff, Tag, EyeOff, Store, ArrowRight } from 'lucide-react'
import { Panel, CopyRow, Steps, Notice, SideLabel, useCopy } from './ui'

const STEPS = [
  {
    title: 'Create a free Merchant Center account',
    body: 'Go to Google Merchant Center and sign up with the Google account you use for your business. It is free.',
    link: 'https://merchants.google.com/',
    linkLabel: 'Open Merchant Center',
  },
  {
    title: 'Confirm your website',
    body: 'Merchant Center will ask you to verify and claim your store address. Paste your store link when it asks for your website.',
  },
  {
    title: 'Add your feed',
    body: 'Under Products, choose to add a product source and pick the scheduled fetch option. Paste the feed link as the file URL and set it to fetch daily.',
  },
  {
    title: 'Turn on free listings',
    body: 'In the free listings section, opt in. Google reviews new accounts, which usually takes a few days, then your products can start showing in search results at no cost.',
  },
]

const naira = (v) => `₦${Number(v || 0).toLocaleString('en-NG')}`
const photoOf = (p) => p.imageUrl || p.imageUrls?.[0] || ''

/** Why product-feed.js would leave a product out, or '' if it goes in. */
function skipReason(p) {
  if (p.isActive === false) return 'hidden'
  if (!(Number(p.price) > 0)) return 'price'
  if (!String(p.name || '').trim()) return 'name'
  if (!photoOf(p)) return 'photo'
  return ''
}
const REASONS = {
  hidden: [EyeOff, 'Hidden from your store'],
  price: [Tag, 'No price'],
  name: [Tag, 'No name'],
  photo: [ImageOff, 'No photo'],
}

export default function GoogleFeedTab({ store, storeUrl, seoActive, eligible, products = [], navigateTo }) {
  const [copied, copy] = useCopy()

  const slug = store?.storeName || ''
  const feedUrl = `https://sellapage.com.ng/${slug}/feed.xml`
  const publicUrl = storeUrl || `https://sellapage.com.ng/${slug}`
  const name = store?.businessName || slug

  const ready = eligible && seoActive
  const going = products.filter((p) => !skipReason(p))
  const skipped = products.filter((p) => skipReason(p))
  const checks = [
    ['On Growth or above', eligible],
    ['Indexing switched on in Get found', seoActive],
    [`Products ready for Google: ${going.length} of ${products.length}`, going.length > 0],
  ]
  const done = checks.filter(([, ok]) => ok).length

  return (
    <div className="grid grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1fr)_340px] xl:grid-cols-[minmax(0,1fr)_380px]">
      <div className="min-w-0 space-y-4">
        <Panel icon={ShoppingBag} title="Free listings on Google" sub="Your products on Google Search, the Shopping tab and Google Images without paying for ads. Sellapage keeps the list up to date, so you only set this up once.">
          <ul className="grid grid-cols-1 gap-2 sm:grid-cols-3">
            {checks.map(([label, ok]) => (
              <li key={label} className={`flex items-start gap-2 rounded-xl px-3 py-2.5 text-[12.5px] font-semibold ${ok ? 'bg-forest-50 text-forest-800' : 'bg-gray-50 text-gray-500'}`}>
                {ok ? <CheckCircle2 size={16} className="mt-px flex-shrink-0 text-forest-600" /> : <Circle size={16} className="mt-px flex-shrink-0 text-gray-300" />}{label}
              </li>
            ))}
          </ul>
        </Panel>

        {!eligible && (
          <Notice tone="lock" title="Available on Growth and above" action={navigateTo && <button type="button" onClick={() => navigateTo('billing')} className="flex-shrink-0 self-center rounded-lg bg-amber-600 px-3 py-1.5 text-[12px] font-bold text-white">See plans</button>}>
            Upgrade to publish your catalogue to Google.
          </Notice>
        )}
        {eligible && !seoActive && (
          <Notice tone="warn" title="Turn on indexing first">
            Your feed stays private until you switch on search engine and AI indexing in Get found. That switch is what tells us you want to be listed publicly.
          </Notice>
        )}

        <Panel title="Your links" sub="Paste these into Merchant Center. The feed link is not your shop link, so do not share it with customers.">
          <div className={`space-y-4 ${ready ? '' : 'opacity-60'}`}>
            <CopyRow label="Feed link" hint="Products, prices and stock, refreshed by Google" value={feedUrl} mono copied={copied === 'feed'} onCopy={() => copy(feedUrl, 'feed')} disabled={!ready} />
            <CopyRow label="Store link" hint="For when Merchant Center verifies your website" value={publicUrl} mono copied={copied === 'store'} onCopy={() => copy(publicUrl, 'store')} />
          </div>
        </Panel>

        <Panel title="How to set it up" sub="About ten minutes, once.">
          <Steps steps={STEPS} />
        </Panel>

        <Panel title="What gets sent">
          <ul className="grid grid-cols-1 gap-2 text-[12.5px] leading-relaxed text-gray-600 sm:grid-cols-2">
            {[
              'Name, description, photo, price and stock status for each product.',
              'Items with no photo, no price, or that you have hidden are left out, because Google rejects them.',
              'Prices are sent in naira, exactly as you set them.',
              'Google refetches on its own, so new products appear without you doing anything.',
            ].map((l) => <li key={l} className="flex items-start gap-2 rounded-xl bg-gray-50 px-3 py-2.5"><CheckCircle2 size={15} className="mt-0.5 flex-shrink-0 text-forest-600" />{l}</li>)}
          </ul>
        </Panel>
      </div>

      <aside className="min-w-0 space-y-4 lg:sticky lg:top-4 lg:self-start">
        <div>
          <SideLabel>On Google Shopping</SideLabel>
          <Panel>
            <div className="flex items-center gap-2 rounded-full border border-gray-200 px-3.5 py-2 text-[12px] text-gray-500">
              <span className="font-bold"><span className="text-[#4285F4]">G</span><span className="text-[#EA4335]">o</span><span className="text-[#FBBC05]">o</span><span className="text-[#4285F4]">g</span><span className="text-[#34A853]">l</span><span className="text-[#EA4335]">e</span></span>
              <span className="truncate">{going[0]?.name || 'your products'}</span>
            </div>
            <div className="mt-2 flex gap-4 border-b border-gray-100 px-1 text-[11.5px] text-gray-500"><span>All</span><span className="border-b-2 border-[#1a73e8] pb-1.5 font-semibold text-[#1a73e8]">Shopping</span><span>Images</span></div>
            {going.length ? (
              <div className="mt-3 grid grid-cols-2 gap-2.5">
                {going.slice(0, 4).map((p) => (
                  <div key={p.id} className="overflow-hidden rounded-xl border border-gray-100">
                    <img src={photoOf(p)} alt="" loading="lazy" className="aspect-square w-full bg-gray-50 object-cover" />
                    <div className="p-2">
                      <p className="line-clamp-2 text-[11.5px] leading-snug text-gray-800">{p.name}</p>
                      <p className="mt-1 text-[12.5px] font-bold text-gray-900">{naira(p.price)}</p>
                      <p className="truncate text-[10.5px] text-gray-500">{name}</p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="mt-3 rounded-xl bg-gray-50 p-5 text-center">
                <Store size={22} className="mx-auto text-gray-300" />
                <p className="mt-2 text-[13px] font-bold text-gray-700">No products ready yet</p>
                <p className="mt-0.5 text-[12px] text-gray-500">A product needs a photo and a price to be listed.</p>
                {navigateTo && <button type="button" onClick={() => navigateTo('products')} className="mt-3 inline-flex items-center gap-1 text-[12.5px] font-bold text-forest-700">Go to products <ArrowRight size={14} /></button>}
              </div>
            )}
            <p className="mt-3 text-[11.5px] leading-relaxed text-gray-400">Your own products, as Google tends to show them. Google decides the final look and where they rank.</p>
          </Panel>
        </div>

        {products.length > 0 && (
          <Panel title="Products in your feed" sub={`${done === checks.length ? 'Ready to go.' : 'Once the checks above are done.'}`}>
            <div className="flex items-center gap-3">
              <div className="h-2.5 flex-1 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-forest-600 transition-[width] duration-700" style={{ width: `${(going.length / products.length) * 100}%` }} /></div>
              <span className="text-[12.5px] font-bold tabular-nums text-gray-800">{going.length}/{products.length}</span>
            </div>
            {skipped.length > 0 && (
              <ul className="mt-3 max-h-56 space-y-1.5 overflow-y-auto">
                {skipped.slice(0, 30).map((p) => {
                  const [Icon, why] = REASONS[skipReason(p)]
                  return (
                    <li key={p.id} className="flex items-center gap-2.5 rounded-xl bg-gray-50 px-3 py-2">
                      <span className="min-w-0 flex-1 truncate text-[12.5px] font-semibold text-gray-700">{p.name || 'Untitled product'}</span>
                      <span className="inline-flex flex-shrink-0 items-center gap-1 rounded-full bg-white px-2 py-0.5 text-[11px] font-semibold text-amber-700 ring-1 ring-amber-100"><Icon size={12} />{why}</span>
                    </li>
                  )
                })}
              </ul>
            )}
          </Panel>
        )}
      </aside>
    </div>
  )
}
